version: '3.9'

services:
  mysql:
    image: mysql:8.1.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ROOT
      MYSQL_DATABASE: Cosateca
      MYSQL_USER: cosateca_owner
      MYSQL_PASSWORD: cosateca_own3r
      LANG: C.UTF_8
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - "./volumes/mysql/db:/var/lib/mysql"
      - "./populate_database_servidor_final.sql:/docker-entrypoint-initdb.d/populate_database_servidor_final.sql"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u $${MYSQL_USER} -p$${MYSQL_ROOT_PASSWORD}"]
      interval: 1s
      timeout: 2s
      retries: 30
    restart: on-failure

  django:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    container_name: django
    ports:
      - '8000:8000'
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ".:/usr/src/app"
    restart: on-failure

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - "./volumes/redis:/data"
    depends_on:
      - django
    command: redis-server --appendonly yes

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - "./volumes/minio_storage:/data"
    depends_on:
      - django
    environment:
      MINIO_ROOT_USER: cosateca
      MINIO_ROOT_PASSWORD: cosateca
    command: server /data --console-address ":9001"